# Python 入门实操教程

# 环境检查

先确认当前 Python 环境是否可以正常运行。

In [2]:
import sys

print("Python 版本：", sys.version)
print("环境检查完成")

Python 版本： 3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0]
环境检查完成

# 变量与基本数据类型

变量可以理解为给数据起名字。Python 中常见的基础数据类型包括整数、浮点数、字符串、布尔值和空值。

In [2]:
age = 20
height = 1.75
name = "小明"
is_student = True
nothing = None

print(age, type(age))
print(height, type(height))
print(name, type(name))
print(is_student, type(is_student))
print(nothing, type(nothing))

20 <class 'int'>
1.75 <class 'float'>
小明 <class 'str'>
True <class 'bool'>
None <class 'NoneType'>

## 类型转换

真实项目中，经常需要把字符串转换成数字，或者把数字转换成字符串。

In [3]:
x = "100"
y = int(x)

price = 19.9
price_text = str(price)

print(y + 20)
print("价格是：" + price_text)

120
价格是：19.9

# 字符串操作

字符串是 Python 中最常用的数据类型之一，常用于处理文本、提示词、日志、文件路径等内容。

In [4]:
text = "Python is useful and Python is fun"

print(text.lower())
print(text.upper())
print(text.replace("Python", "AI"))
print(text.count("Python"))
print(text.startswith("Python"))
print(text.endswith("fun"))

python is useful and python is fun
PYTHON IS USEFUL AND PYTHON IS FUN
AI is useful and AI is fun
2
True
True

## 字符串切片

切片用于从字符串中取出一部分内容。

In [5]:
s = "Hello Python"

print(s[0])
print(s[-1])
print(s[0:5])
print(s[6:])
print(s[:5])
print(s[::-1])

H
n
Hello
Python
Hello
nohtyP olleH

## f-string 格式化

f-string 是现代 Python 中非常推荐的字符串拼接方式。

In [6]:
name = "小明"
score = 92.5678

message = f"{name} 的成绩是 {score:.2f} 分"
print(message)

小明 的成绩是 92.57 分

# 列表

列表用于保存一组有顺序的数据，可以增删改查。

In [3]:
scores = [88, 92, 75, 100, 67, "12"]

print(scores)
print(scores[0])
print(scores[-1])

scores.append(95)
print(scores)

scores.remove(75)
print(scores)

scores[1] = 90
print(scores)

[88, 92, 75, 100, 67, '12']
88
12
[88, 92, 75, 100, 67, '12', 95]
[88, 92, 100, 67, '12', 95]
[88, 90, 100, 67, '12', 95]

## 列表常用操作

列表可以进行排序、求和、取最大值、取最小值、计算长度等操作。

In [8]:
scores = [88, 92, 75, 100, 67]

print("数量：", len(scores))
print("总分：", sum(scores))
print("最高分：", max(scores))
print("最低分：", min(scores))
print("平均分：", sum(scores) / len(scores))

print("升序：", sorted(scores))
print("降序：", sorted(scores, reverse=True))

数量： 5
总分： 422
最高分： 100
最低分： 67
平均分： 84.4
升序： [67, 75, 88, 92, 100]
降序： [100, 92, 88, 75, 67]

## 列表推导式

列表推导式可以用更简洁的方式生成新列表。

In [9]:
numbers = [1, 2, 3, 4, 5]

squares = [x ** 2 for x in numbers]
even_numbers = [x for x in numbers if x % 2 == 0]

print(squares)
print(even_numbers)

[1, 4, 9, 16, 25]
[2, 4]

# 元组、集合与字典

元组适合保存不可修改的一组数据，集合适合保存不重复的数据，字典适合保存键值对数据。

In [10]:
point = (10, 20)
print("元组：", point)

tags = {"Python", "AI", "Python", "Data"}
print("集合会自动去重：", tags)

student = {
    "name": "小明",
    "age": 20,
    "score": 92
}

print("字典：", student)
print("姓名：", student["name"])

元组： (10, 20)
集合会自动去重： {'AI', 'Python', 'Data'}
字典： {'name': '小明', 'age': 20, 'score': 92}
姓名： 小明

## 字典实操

字典非常适合表示一条结构化记录，例如一个用户、一个商品、一篇文章。

In [11]:
product = {
    "id": 1001,
    "name": "无线鼠标",
    "price": 59.9,
    "stock": 120
}

product["price"] = 49.9
product["sales"] = 35

print(product)
print("所有键：", list(product.keys()))
print("所有值：", list(product.values()))
print("所有键值对：", list(product.items()))

{'id': 1001, 'name': '无线鼠标', 'price': 49.9, 'stock': 120, 'sales': 35}
所有键： ['id', 'name', 'price', 'stock', 'sales']
所有值： [1001, '无线鼠标', 49.9, 120, 35]
所有键值对： [('id', 1001), ('name', '无线鼠标'), ('price', 49.9), ('stock', 120), ('sales', 35)]

# 条件判断

条件判断用于根据不同情况执行不同逻辑。

In [12]:
score = 86

if score >= 90:
    level = "优秀"
elif score >= 80:
    level = "良好"
elif score >= 60:
    level = "及格"
else:
    level = "不及格"

print(level)

良好

## 多条件判断

可以使用 and、or、not 组合多个条件。

In [13]:
age = 22
has_ticket = True

if age >= 18 and has_ticket:
    print("可以入场")
else:
    print("不能入场")

is_vip = False

if has_ticket or is_vip:
    print("允许进入")
else:
    print("不允许进入")

可以入场
允许进入

# 循环

循环用于重复执行一段逻辑。常见循环有 for 和 while。

In [14]:
names = ["张三", "李四", "王五"]

for name in names:
    print("你好，", name)

你好， 张三
你好， 李四
你好， 王五

## range 循环

range 常用于生成整数序列。

In [15]:
for i in range(5):
    print(i)

print("从 1 到 5：")
for i in range(1, 6):
    print(i)

0
1
2
3
4
从 1 到 5：
1
2
3
4
5

## break 与 continue

break 用于提前结束循环，continue 用于跳过本轮循环。

In [16]:
for i in range(1, 11):
    if i == 8:
        break
    if i % 2 == 0:
        continue
    print(i)

1
3
5
7

# 函数

函数用于封装可复用的逻辑，让代码更清晰。

In [17]:
def greet(name):
    return f"你好，{name}"

message = greet("小明")
print(message)

你好，小明

## 带默认参数的函数

默认参数可以让函数调用更灵活。

In [18]:
def calculate_total(price, quantity=1, discount=1.0):
    return price * quantity * discount

print(calculate_total(100))
print(calculate_total(100, quantity=3))
print(calculate_total(100, quantity=3, discount=0.8))

100.0
300.0
240.0

## 函数练习

下面写一个函数，用来判断成绩等级。

In [19]:
def get_score_level(score):
    if score >= 90:
        return "优秀"
    elif score >= 80:
        return "良好"
    elif score >= 60:
        return "及格"
    else:
        return "不及格"

test_scores = [95, 82, 70, 40]

for score in test_scores:
    print(score, get_score_level(score))

95 优秀
82 良好
70 及格
40 不及格

# 模块与标准库

Python 标准库提供了很多常用工具，例如数学、随机数、时间、路径处理等。

In [20]:
import math
import random
from datetime import datetime

print("平方根：", math.sqrt(16))
print("随机整数：", random.randint(1, 100))
print("当前时间：", datetime.now())

平方根： 4.0
随机整数： 22
当前时间： 2026-07-07 16:49:45.254798

# 文件读写

文件读写是 Python 自动化和数据处理的基础。

In [21]:
content = '''Python 入门教程
这是第一行内容
这是第二行内容
'''

with open("demo.txt", "w", encoding="utf-8") as f:
    f.write(content)

print("文件写入完成")

文件写入完成

In [22]:
with open("demo.txt", "r", encoding="utf-8") as f:
    text = f.read()

print(text)

Python 入门教程
这是第一行内容
这是第二行内容

# 异常处理

异常处理可以让程序在遇到错误时不直接崩溃，而是给出更友好的处理方式。

In [23]:
text = "abc"

try:
    number = int(text)
    print(number)
except ValueError:
    print("转换失败：文本不是合法数字")

转换失败：文本不是合法数字

# 面向对象基础

类可以用来描述一类对象。对象可以拥有属性和方法。

In [24]:
class Student:
    def __init__(self, name, score):
        self.name = name
        self.score = score

    def get_level(self):
        if self.score >= 90:
            return "优秀"
        elif self.score >= 80:
            return "良好"
        elif self.score >= 60:
            return "及格"
        else:
            return "不及格"

    def introduce(self):
        return f"我是 {self.name}，成绩是 {self.score}，等级是 {self.get_level()}"

student = Student("小明", 92)
print(student.introduce())

我是 小明，成绩是 92，等级是 优秀

# 实操项目：学生成绩管理

下面实现一个简单的学生成绩管理系统，包含添加学生、查看学生、计算平均分、找最高分等功能。

In [25]:
students = []

def add_student(name, score):
    student = {
        "name": name,
        "score": score
    }
    students.append(student)

def show_students():
    if not students:
        print("暂无学生数据")
        return

    for student in students:
        print(f"{student['name']}：{student['score']} 分")

def get_average_score():
    if not students:
        return 0

    total = sum(student["score"] for student in students)
    return total / len(students)

def get_top_student():
    if not students:
        return None

    return max(students, key=lambda student: student["score"])

add_student("小明", 92)
add_student("小红", 85)
add_student("小刚", 73)
add_student("小丽", 96)

show_students()
print("平均分：", get_average_score())
print("最高分学生：", get_top_student())

小明：92 分
小红：85 分
小刚：73 分
小丽：96 分
平均分： 86.5
最高分学生： {'name': '小丽', 'score': 96}

# 实操项目：文本词频统计

这个项目会读取一段文本，统计每个词出现的次数。

In [26]:
text = '''
python is useful
python is easy
data is powerful
python and data are important
'''

words = text.lower().split()
word_count = {}

for word in words:
    if word not in word_count:
        word_count[word] = 1
    else:
        word_count[word] += 1

print(word_count)

sorted_word_count = sorted(word_count.items(), key=lambda item: item[1], reverse=True)

for word, count in sorted_word_count:
    print(word, count)

{'python': 3, 'is': 3, 'useful': 1, 'easy': 1, 'data': 2, 'powerful': 1, 'and': 1, 'are': 1, 'important': 1}
python 3
is 3
data 2
useful 1
easy 1
powerful 1
and 1
are 1
important 1

# 简单数据分析

如果环境中安装了 pandas，可以用它处理表格数据。

In [27]:
try:
    import pandas as pd

    data = {
        "name": ["小明", "小红", "小刚", "小丽"],
        "age": [20, 21, 19, 22],
        "score": [92, 85, 73, 96]
    }

    df = pd.DataFrame(data)

    display(df)
    print("平均成绩：", df["score"].mean())
    print("最高成绩：", df["score"].max())

    df["level"] = df["score"].apply(get_score_level)
    display(df)

except ImportError:
    print("当前环境没有安装 pandas，可以先运行：pip install pandas")

  name  age  score
0   小明   20     92
1   小红   21     85
2   小刚   19     73
3   小丽   22     96

平均成绩： 86.5
最高成绩： 96

  name  age  score level
0   小明   20     92    优秀
1   小红   21     85    良好
2   小刚   19     73    及格
3   小丽   22     96    优秀

# 综合练习

下面完成一个商品销售额统计任务：创建商品列表，计算每个商品的销售额，找出销售额最高的商品，统计总销售额，并把结果写入文本文件。

In [28]:
products = [
    {"name": "键盘", "price": 199, "sales": 30},
    {"name": "鼠标", "price": 59, "sales": 120},
    {"name": "显示器", "price": 899, "sales": 15},
    {"name": "耳机", "price": 299, "sales": 45}
]

for product in products:
    product["revenue"] = product["price"] * product["sales"]

top_product = max(products, key=lambda product: product["revenue"])
total_revenue = sum(product["revenue"] for product in products)

print("商品数据：")
for product in products:
    print(product)

print("销售额最高的商品：", top_product)
print("总销售额：", total_revenue)

with open("sales_report.txt", "w", encoding="utf-8") as f:
    f.write("销售报告\n")
    for product in products:
        f.write(f"{product['name']}：销售额 {product['revenue']}\n")
    f.write(f"总销售额：{total_revenue}\n")

print("销售报告已写入 sales_report.txt")

商品数据：
{'name': '键盘', 'price': 199, 'sales': 30, 'revenue': 5970}
{'name': '鼠标', 'price': 59, 'sales': 120, 'revenue': 7080}
{'name': '显示器', 'price': 899, 'sales': 15, 'revenue': 13485}
{'name': '耳机', 'price': 299, 'sales': 45, 'revenue': 13455}
销售额最高的商品： {'name': '显示器', 'price': 899, 'sales': 15, 'revenue': 13485}
总销售额： 39990
销售报告已写入 sales_report.txt